insert into MY_TABLE (ID, INGREDIENT_TYPE, NAME, DESCRIPTION, STATUS)
values  (1, 4, 'Thịt gà', null, 1),
        (2, 4, 'Thịt bò', null, 1),
        (3, 4, 'Thịt lợn', null, 1),
        (4, 4, 'Thịt chim câu', null, 1),
        (5, 5, 'Cải bó xôi', null, 1),
        (6, 5, 'Rau cải xoăn', null, 1),
        (7, 5, 'Bông cải xanh', null, 1),
        (8, 5, 'Bí đỏ', null, 1),
        (9, 6, 'Kiều mạch', null, 1),
        (10, 6, 'Diêm mạch', null, 1),
        (11, 6, 'Hạt kê', null, 1),
        (12, 6, 'Đậu Hà Lan', null, 1),
        (13, 7, 'Gạo', null, 1),
        (14, 7, 'Nui', null, 0);